name: workshop
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=py313h06a4308_0
  - attr=2.5.2=h39aace5_0
  - blosc=1.21.6=he440d0b_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cf_xarray=0.10.7=pyhd8ed1ab_0
  - comm=0.2.1=py313h06a4308_0
  - debugpy=1.8.11=py313h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - esmf=8.9.0=mpi_mpich_h50cdae2_102
  - esmpy=8.9.0=pyhc455866_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - geos=3.13.1=h97f6797_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=mpi_mpich_h958611c_3
  - ipykernel=6.29.5=py313h06a4308_1
  - ipython=9.1.0=py313h06a4308_0
  - ipython_pygments_lexers=1.1.1=py313h06a4308_0
  - jedi=0.19.2=py313h06a4308_0
  - jupyter_client=8.6.3=py313h06a4308_0
  - jupyter_core=5.8.1=py313h06a4308_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.9.0=34_h59b9bed_openblas
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=34_he106b2a_openblas
  - libcurl=8.14.1=h332b0f4_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libfabric=2.2.0=ha770c72_2
  - libfabric1=2.2.0=h3ff6011_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgfortran=15.1.0=h69a702a_4
  - libgfortran5=15.1.0=hcea5267_4
  - libgomp=15.1.0=h767d61c_4
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=34_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=h5eee18b_0
  - libnetcdf=4.9.3=mpi_mpich_h3f6f051_0
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libpnetcdf=1.14.1=mpi_mpich_h3dbf9f6_100
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libsystemd0=257.7=h4e0b6ca_0
  - libudev1=257.7=hbe16f8c_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=h2cb61b6_1
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - matplotlib-inline=0.1.6=py313h06a4308_0
  - mpi=1.0.1=mpich
  - mpich=4.3.1=h79b1c89_103
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py313h06a4308_0
  - netcdf-fortran=4.6.2=mpi_mpich_hf41eadc_2
  - numba=0.61.2=py313h50b8c88_1
  - numpy=2.2.6=py313h17eae1a_0
  - openssl=3.5.2=h26f9b46_0
  - packaging=25.0=py313h06a4308_0
  - pandas=2.3.2=py313h08cd8bf_0
  - parallelio=2_6_6=mpi_mpich_h66c247d_103
  - parso=0.8.4=py313h06a4308_0
  - pexpect=4.9.0=py313h06a4308_0
  - pip=25.2=pyhc872135_0
  - platformdirs=4.3.7=py313h06a4308_0
  - prompt-toolkit=3.0.43=py313h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py313h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.19.1=py313h06a4308_0
  - python=3.13.2=hf636f53_101_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=0_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=26.2.0=py313h6a678d5_0
  - rdma-core=59.0=hecca717_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py313h06a4308_0
  - shapely=2.1.1=py313h393e2d1_1
  - six=1.17.0=py313h06a4308_0
  - snappy=1.2.2=h03e3b7b_0
  - sparse=0.17.0=pyhcf101f3_0
  - sqlite=3.50.4=hbc0de68_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.13=noxft_hd72426e_102
  - tornado=6.5.1=py313h5eee18b_0
  - traitlets=5.14.3=py313h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - ucx=1.19.0=hc93acc0_3
  - wcwidth=0.2.13=py313h06a4308_0
  - wheel=0.45.1=py313h06a4308_0
  - xarray=2025.9.0=pyhd8ed1ab_0
  - xesmf=0.8.10=pyhd8ed1ab_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - affine==2.4.0
      - anyio==4.10.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.5
      - bleach==6.2.0
      - bokeh==3.8.0
      - cartopy==0.25.0
      - certifi==2025.8.3
      - cffi==1.17.1
      - cfgrib==0.9.15.0
      - cftime==1.6.4.post1
      - charset-normalizer==3.4.3
      - click==8.2.1
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - cloudpickle==3.1.1
      - contextily==1.6.2
      - contourpy==1.3.3
      - cycler==0.12.1
      - dask==2025.9.0
      - defusedxml==0.7.1
      - eccodes==2.43.0
      - eccodeslib==2.43.0
      - eckitlib==1.31.4
      - fastjsonschema==2.21.2
      - fckitlib==0.14.0
      - findlibs==0.1.2
      - fonttools==4.59.2
      - fqdn==1.5.1
      - fsspec==2025.9.0
      - geographiclib==2.1
      - geopandas==1.1.1
      - geopy==2.4.1
      - h11==0.16.0
      - h5py==3.14.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.7
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - lark==1.2.2
      - linkify-it-py==2.0.3
      - llvmlite==0.44.0
      - locket==1.0.0
      - logger==1.4
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.6
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - mercantile==1.2.1
      - mistune==3.1.4
      - narwhals==2.5.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - netcdf4==1.7.2
      - notebook-shim==0.2.4
      - pandocfilters==1.5.1
      - panel==1.8.1
      - param==2.2.1
      - partd==1.4.2
      - pillow==11.3.0
      - prometheus-client==0.22.1
      - pycparser==2.22
      - pyogrio==0.11.1
      - pyparsing==3.2.3
      - pyproj==3.7.2
      - pyshp==2.3.1
      - python-json-logger==3.3.0
      - pyviz-comms==3.0.6
      - pyyaml==6.0.2
      - rasterio==1.4.3
      - referencing==0.36.2
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.27.1
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.8
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - toolz==1.0.0
      - tqdm==4.67.1
      - types-python-dateutil==2.9.0.20250822
      - typing-extensions==4.15.0
      - uc-micro-py==1.0.3
      - uri-template==1.3.0
      - urllib3==2.5.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.14
      - xyzservices==2025.4.0
prefix: /inception_users/adah.kibet/anaconda3/envs/workshop
